// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NukeTaskRunner
{
    internal sealed partial class Vsix
    {
        public const string Id = "c5203f5f-4785-4c09-b383-688a100a9f5d";
        public const string Name = "NUKE Task Runner";
        public const string Description = @"Adds support for nuke scripts defined in Build.cs directly in Visual Studio's Task Runner Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen / Sharp Ninja";
        public const string Tags = "nuke, Build.cs, task runner";
    }
}
